### ISSUE TITLE
Use Chrome native way of doing apps

### ISSUE THREAD

**Issue by maelp** [mathix420/free-the-web-apps#10]
While researching this issue, I saw that the solution is actually quite simple (although unfortunately not as simple and shareable as a script):

- navigate to the website in Chrome
- click on the "..." next to the profile icon
- Cast, save and share > Create application

and this does exactly the same as your script, except the window is now standalone, and can be closed using CMD+Q

Perhaps there's a way to automate doing this with your script?

**Comment by mathix420** [comment]
Oh I wasn't aware you could do this without the website having a web manifest! But it still shows differently on linux, which was the main point of me developing this software.
I will give a bit more information about this on the website tho.

FTWA on the left and PWA on the right.

![image](https://github.com/user-attachments/assets/e7a26f12-8682-4bb6-92fd-c120bbfc7684)

**Comment by mathix420** [comment]
I put this as stale for now, but I'm still open to contributions
