### ISSUE TITLE
Name not respecting spaces or dashes

### ISSUE THREAD

**Issue by KingMob** [mathix420/free-the-web-apps#16]
**Describe the bug**

If I type something like "big-AGI" for the name, the created app name is something like "BigAgi", which I don't want.

**To Reproduce**
1. Go to https://ftwa.mathix.dev/
2. Select a valid URL and icon.
3. For the name, put in something like "foo-BAR"
4. Choose macOS and Firefox
5. Click "Free..." button, and execute the curl shell command.
6. Go to /Applications
7. See the name is different

**Expected behavior**
I expect it to have the same as the name I wrote

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Chrome, FF Dev Edition
 - Version FF 132.0b9, Chrome 130.0.6723.70

**Additional context**

**Comment by mathix420** [comment]
Hi @KingMob, can you please let me know if everything is working as expected now?

**Comment by KingMob** [comment]
It works!

**Comment by mathix420** [comment]
perfect! thanks again for raising the issue and sorry for the delay but I have other projects that have a bit more priority
