### ISSUE TITLE
Doesn't work with Firefox Developer Edition

### ISSUE THREAD

**Issue by KingMob** [mathix420/free-the-web-apps#3]
The shell command from the website doesn't work with FF Dev Edition.

**To Reproduce**
1. Go to [FTWA](https://ftwa.mathix.dev/)
2. Under "App Gallery", replace the default Firefox path with the Firefox Developer Edition path: "/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox"
3. Scroll down to some sample app/site, and copy the command (e.g., `sh -ec "$(curl -fsSL 'https://ftwa.mathix.dev/v/netflix?os=macos&bw=firefox&path=%2FApplications%2FFirefox%20Developer%20Edition.app%2FContents%2FMacOS%2Ffirefox')"`)
4. Paste in shell, and see the error: 
 
```
Setting up Firefox...
sh: line 13: /Applications/Firefox: No such file or directory"
```

**Expected behavior**
I expected it to be able to handle spaces in the path.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.7
 - Browser Firefox Developer Edition
 - Version 131.0b9

**Comment by mathix420** [comment]
Ah yes I see, for a quick workaround, you can add a backslash before each space in the custom path.
I'll escape this automatically in the next update, thanks for reporting the issue!

**Comment by KingMob** [comment]
It worked! Many thanks for this cool trick!

Unfortunately, while the initial "Netflix" has an icon and is searchable separately, once opened, it's another copy of FF in the app list. Do you know of a way to make that appear like Netflix, too?

**Comment by mathix420** [comment]
This is not intended, the app list should be showing the icon. Can you send me a screenshot?

**Comment by KingMob** [comment]
....Weird, the problem sorted itself out. Maybe macOS caught up with some indexing/updating? Or does FF have a hand in this somehow?

Only thing I changed was to install my 1Password extension to make logging in easier...

**Comment by mathix420** [comment]
> ....Weird, the problem sorted itself out. Maybe macOS caught up with some indexing/updating? Or does FF have a hand in this somehow?

Can't say for sure, but firefox shouldn't have anything to do with this. Don't hesitate to send if this occurs again.

> Only thing I changed was to install my 1Password extension to make logging in easier...

Yes that's a good idea, with chromium browsers every extensions are still present, I will add some documentation on how to do so on firefox.
