### ISSUE TITLE
"Real app"

### ISSUE THREAD

**Issue by maelp** [mathix420/free-the-web-apps#4]
Very nice!

Right now when running an app, it shows (obviously) as Google Chrome (on osX at least). Is there a way to have the app icon appear as a "separate app" (icon in the dock / app toggler / possibly an option for a menubar icon mode?)

This would also allow some programs that redirect sound to work properly (eg sometimes I run a music website and I'd like only this to be redirected to my HomePod)

**Comment by mathix420** [comment]
Maybe this could be a solution: https://apple.stackexchange.com/questions/230390/how-to-open-new-windows-as-separate-application-instances-for-chrome-terminal
Could you have a look? I don't have a mac personally so I can't test such things rapidly.

**Comment by maelp** [comment]
Doesn't seem to work

**Comment by mathix420** [comment]
Okay, too bad then. I guess the only other option is to create an electron client, but it's way to far from the goals of this project. I close this issue for now but would love to reopen if someone have new informations.

**Comment by maelp** [comment]
Those params (in particular --window-title="App Name" --app="app url") are interesting, as it makes it look "more" like a native app https://gist.github.com/thenoseman/710011
