### ISSUE TITLE
[APP] - Spotify

### ISSUE THREAD

**Issue by maelp** [mathix420/free-the-web-apps#5]
### App name

Spotify

### App URL

https://spotify.com/

### App description

Spotify player

### App logo URL

https://e7.pngegg.com/pngimages/438/839/png-clipart-spotify-logo-streaming-media-spotify-icon-text-logo-thumbnail.png

### Mac logo

![4a5b168d2a16011c308469cb847b7363_Spotify_1024x1024x32](https://github.com/user-attachments/assets/d3d1d16d-e781-432c-9c73-a0a83f25f544)

### Logo size (in px)

352

**Comment by mathix420** [comment]
https://ftwa.mathix.dev/store#app-spotify
