### ISSUE TITLE
Bug when using 1024x1024 images for osX

### ISSUE THREAD

**Issue by maelp** [mathix420/free-the-web-apps#6]
I'm using this URL in your webapp to create the app script https://i.imgur.com/llfSMaN.png which is 1024x1024 but the script says there's an error with the size

**Comment by mathix420** [comment]
It seems to be an issue with imgur rather than FTWA, if you don't have any cookies the url will redirect to an HTML document and not the actual image.
Try to upload the image on imgbb.com to confirm.
